feeds:
  - uri: "at://did:plc:naxgru5hoiqlaosuneywxuxz/app.bsky.feed.generator/fp-support"
    name: "Frontpage Support"
    description: "The Frontpage Support feed."
    allow:
      - did:plc:naxgru5hoiqlaosuneywxuxz # feeds.unravel.fyi
      - did:plc:2xau7wbgdq4phuou2ypwuen7 # Tom
      - did:plc:lhldvebr3louno6ylqen3u2x # Will
      - did:plc:fdf3zzst2hwcbqvdnjcxubki # Jake
      - did:plc:hjhhs7pnc3eoii2xpyvwcsge # Damien
      - did:plc:3ov53se5dtzvqtto27vxpcp3 # Tim
    deny: "at://did:plc:4acsffvbo4niovge362ptijz/app.bsky.feed.post/3la5bsyzj3j23"
    matchers:
      - path: "$.commit.record.facets[*].features[?(@['$type'] == 'app.bsky.richtext.facet#tag')].tag"
        values: ["frontpage.fyi"]
        type: sequence
      - path: "$.commit.record.facets[*].features[?(@['$type'] == 'app.bsky.richtext.facet#link')].uri"
        value: "https://frontpage.fyi"
        type: prefix
      - path: "$.commit.record.facets[*].features[?(@['$type'] == 'app.bsky.richtext.facet#link')].uri"
        value: "http://frontpage.fyi"
        type: prefix
      - path: "$.commit.record.embed.external.uri"
        value: "https://frontpage.fyi"
        type: prefix
      - path: "$.commit.record.embed.external.uri"
        value: "http://frontpage.fyi"
        type: prefix
      - path: "$.commit.record.facets[*].features[?(@['$type'] == 'app.bsky.richtext.facet#mention')].did"
        value: "did:plc:klmr76mpewpv7rtm3xgpzd7x"
        type: equal
